/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.example.submoda.Helper;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    private void nextThingToDo() {
        System.out.println("here is the next thing to do...");
    }

    public static void main(String[] args) {
        App app = new App();
        System.out.println(app.getGreeting());
        app.nextThingToDo();
        System.out.println(Helper.message());
    }
}
